import Footer from "@/components/footer/Footer";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ProductsLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section>
      {children}
      <Footer />
    </section>
  );
}
